#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DamageDecal_BubbleLens

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_DamageDecal_BubbleLens.BP_DamageDecal_BubbleLens_C.ExecuteUbergraph_BP_DamageDecal_BubbleLens
// 0x0004 (0x0004 - 0x0000)
struct BP_DamageDecal_BubbleLens_C_ExecuteUbergraph_BP_DamageDecal_BubbleLens final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DamageDecal_BubbleLens_C_ExecuteUbergraph_BP_DamageDecal_BubbleLens) == 0x000004, "Wrong alignment on BP_DamageDecal_BubbleLens_C_ExecuteUbergraph_BP_DamageDecal_BubbleLens");
static_assert(sizeof(BP_DamageDecal_BubbleLens_C_ExecuteUbergraph_BP_DamageDecal_BubbleLens) == 0x000004, "Wrong size on BP_DamageDecal_BubbleLens_C_ExecuteUbergraph_BP_DamageDecal_BubbleLens");
static_assert(offsetof(BP_DamageDecal_BubbleLens_C_ExecuteUbergraph_BP_DamageDecal_BubbleLens, EntryPoint) == 0x000000, "Member 'BP_DamageDecal_BubbleLens_C_ExecuteUbergraph_BP_DamageDecal_BubbleLens::EntryPoint' has a wrong offset!");

}

