#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Skill_TheWorld

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AJB_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_Skill_TheWorld.WB_Skill_TheWorld_C
// 0x0010 (0x0290 - 0x0280)
class UWB_Skill_TheWorld_C final : public UAJBInGameSkillWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(Transient, DuplicateTransient)
	class UWB_SkillPartsTimer_C*                  TimerWidget;                                       // 0x0288(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WB_Skill_TheWorld(int32 EntryPoint);
	void ChangeColor(bool bEnemy);
	void UpdateDisplay(float Value);
	void End();
	void Start();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_Skill_TheWorld_C">();
	}
	static class UWB_Skill_TheWorld_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_Skill_TheWorld_C>();
	}
};
static_assert(alignof(UWB_Skill_TheWorld_C) == 0x000008, "Wrong alignment on UWB_Skill_TheWorld_C");
static_assert(sizeof(UWB_Skill_TheWorld_C) == 0x000290, "Wrong size on UWB_Skill_TheWorld_C");
static_assert(offsetof(UWB_Skill_TheWorld_C, UberGraphFrame) == 0x000280, "Member 'UWB_Skill_TheWorld_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_Skill_TheWorld_C, TimerWidget) == 0x000288, "Member 'UWB_Skill_TheWorld_C::TimerWidget' has a wrong offset!");

}

