#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_VictoryShotCameraflash

#include "Basic.hpp"


namespace SDK::Params
{

// Function WB_VictoryShotCameraflash.WB_VictoryShotCameraFlash_C.ExecuteUbergraph_WB_VictoryShotCameraFlash
// 0x0004 (0x0004 - 0x0000)
struct WB_VictoryShotCameraFlash_C_ExecuteUbergraph_WB_VictoryShotCameraFlash final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_VictoryShotCameraFlash_C_ExecuteUbergraph_WB_VictoryShotCameraFlash) == 0x000004, "Wrong alignment on WB_VictoryShotCameraFlash_C_ExecuteUbergraph_WB_VictoryShotCameraFlash");
static_assert(sizeof(WB_VictoryShotCameraFlash_C_ExecuteUbergraph_WB_VictoryShotCameraFlash) == 0x000004, "Wrong size on WB_VictoryShotCameraFlash_C_ExecuteUbergraph_WB_VictoryShotCameraFlash");
static_assert(offsetof(WB_VictoryShotCameraFlash_C_ExecuteUbergraph_WB_VictoryShotCameraFlash, EntryPoint) == 0x000000, "Member 'WB_VictoryShotCameraFlash_C_ExecuteUbergraph_WB_VictoryShotCameraFlash::EntryPoint' has a wrong offset!");

}

