#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BI_HighlightEvents

#include "Basic.hpp"

#include "BI_HighlightEvents_classes.hpp"


namespace SDK
{

// Function BI_HighlightEvents.BI_HighlightEvents_C.OnHighlightPlayBegin
// (Public, BlueprintCallable, BlueprintEvent)

void IBI_HighlightEvents_C::OnHighlightPlayBegin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BI_HighlightEvents_C", "OnHighlightPlayBegin");

	UObject::ProcessEvent(Func, nullptr);
}

}

