#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBInGamePlayerCameraManager

#include "Basic.hpp"

#include "BP_AJBInGamePlayerCameraManager_classes.hpp"
#include "BP_AJBInGamePlayerCameraManager_parameters.hpp"


namespace SDK
{

// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.ExecuteUbergraph_BP_AJBInGamePlayerCameraManager
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBInGamePlayerCameraManager_C::ExecuteUbergraph_BP_AJBInGamePlayerCameraManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "ExecuteUbergraph_BP_AJBInGamePlayerCameraManager");

	Params::BP_AJBInGamePlayerCameraManager_C_ExecuteUbergraph_BP_AJBInGamePlayerCameraManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.ChangeCrimsonDimensionEffect
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bEnable                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_AJBInGamePlayerCameraManager_C::ChangeCrimsonDimensionEffect(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "ChangeCrimsonDimensionEffect");

	Params::BP_AJBInGamePlayerCameraManager_C_ChangeCrimsonDimensionEffect Parms{};

	Parms.bEnable = bEnable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.OnResetPostProcess
// (BlueprintCallable, BlueprintEvent)

void ABP_AJBInGamePlayerCameraManager_C::OnResetPostProcess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "OnResetPostProcess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.ChangeTheWorldEffect
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enable                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_AJBInGamePlayerCameraManager_C::ChangeTheWorldEffect(bool Enable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "ChangeTheWorldEffect");

	Params::BP_AJBInGamePlayerCameraManager_C_ChangeTheWorldEffect Parms{};

	Parms.Enable = Enable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.OpenTickGate
// (BlueprintCallable, BlueprintEvent)

void ABP_AJBInGamePlayerCameraManager_C::OpenTickGate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "OpenTickGate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBInGamePlayerCameraManager_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "ReceiveTick");

	Params::BP_AJBInGamePlayerCameraManager_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_AJBInGamePlayerCameraManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_AJBInGamePlayerCameraManager_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.SetPostProcessMaterialBlendWeight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MaterialIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Weight                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBInGamePlayerCameraManager_C::SetPostProcessMaterialBlendWeight(int32 MaterialIndex, float Weight)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "SetPostProcessMaterialBlendWeight");

	Params::BP_AJBInGamePlayerCameraManager_C_SetPostProcessMaterialBlendWeight Parms{};

	Parms.MaterialIndex = MaterialIndex;
	Parms.Weight = Weight;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.SetPostProcessMaterialObject
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MaterialIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInsert                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_AJBInGamePlayerCameraManager_C::SetPostProcessMaterialObject(int32 MaterialIndex, class UObject* Object, bool bInsert)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "SetPostProcessMaterialObject");

	Params::BP_AJBInGamePlayerCameraManager_C_SetPostProcessMaterialObject Parms{};

	Parms.MaterialIndex = MaterialIndex;
	Parms.Object = Object;
	Parms.bInsert = bInsert;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.SetPostProcessMaterial
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInterface*               PostProcessMaterial                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PostProcesIndex                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsEnable                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_AJBInGamePlayerCameraManager_C::SetPostProcessMaterial(class UMaterialInterface* PostProcessMaterial, int32& PostProcesIndex, bool IsEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "SetPostProcessMaterial");

	Params::BP_AJBInGamePlayerCameraManager_C_SetPostProcessMaterial Parms{};

	Parms.PostProcessMaterial = PostProcessMaterial;
	Parms.PostProcesIndex = PostProcesIndex;
	Parms.IsEnable = IsEnable;

	UObject::ProcessEvent(Func, &Parms);

	PostProcesIndex = Parms.PostProcesIndex;
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.PrepareDamageAreaDynamicMaterialInstance
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_AJBInGamePlayerCameraManager_C::PrepareDamageAreaDynamicMaterialInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "PrepareDamageAreaDynamicMaterialInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGamePlayerCameraManager.BP_AJBInGamePlayerCameraManager_C.RequestDestroyDefaultListener
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AJBInGamePlayerCameraManager_C::RequestDestroyDefaultListener()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGamePlayerCameraManager_C", "RequestDestroyDefaultListener");

	UObject::ProcessEvent(Func, nullptr);
}

}

