#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBCharacterBehaviorMovement

#include "Basic.hpp"

#include "BP_AJBCharacterBehaviorBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AJBCharacterBehaviorMovement.BP_AJBCharacterBehaviorMovement_C
// 0x0000 (0x0038 - 0x0038)
class UBP_AJBCharacterBehaviorMovement_C final : public UBP_AJBCharacterBehaviorBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AJBCharacterBehaviorMovement_C">();
	}
	static class UBP_AJBCharacterBehaviorMovement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AJBCharacterBehaviorMovement_C>();
	}
};
static_assert(alignof(UBP_AJBCharacterBehaviorMovement_C) == 0x000008, "Wrong alignment on UBP_AJBCharacterBehaviorMovement_C");
static_assert(sizeof(UBP_AJBCharacterBehaviorMovement_C) == 0x000038, "Wrong size on UBP_AJBCharacterBehaviorMovement_C");

}

