#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionsMenu

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_OptionsMenu.WBP_OptionsMenu_C.ExecuteUbergraph_WBP_OptionsMenu
// 0x0004 (0x0004 - 0x0000)
struct WBP_OptionsMenu_C_ExecuteUbergraph_WBP_OptionsMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OptionsMenu_C_ExecuteUbergraph_WBP_OptionsMenu) == 0x000004, "Wrong alignment on WBP_OptionsMenu_C_ExecuteUbergraph_WBP_OptionsMenu");
static_assert(sizeof(WBP_OptionsMenu_C_ExecuteUbergraph_WBP_OptionsMenu) == 0x000004, "Wrong size on WBP_OptionsMenu_C_ExecuteUbergraph_WBP_OptionsMenu");
static_assert(offsetof(WBP_OptionsMenu_C_ExecuteUbergraph_WBP_OptionsMenu, EntryPoint) == 0x000000, "Member 'WBP_OptionsMenu_C_ExecuteUbergraph_WBP_OptionsMenu::EntryPoint' has a wrong offset!");

}

