#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBNetworkTestProxy

#include "Basic.hpp"

#include "BP_AJBNetworkTestProxy_classes.hpp"
#include "BP_AJBNetworkTestProxy_parameters.hpp"


namespace SDK
{

// Function BP_AJBNetworkTestProxy.BP_AJBNetworkTestProxy_C.ExecuteUbergraph_BP_AJBNetworkTestProxy
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBNetworkTestProxy_C::ExecuteUbergraph_BP_AJBNetworkTestProxy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBNetworkTestProxy_C", "ExecuteUbergraph_BP_AJBNetworkTestProxy");

	Params::BP_AJBNetworkTestProxy_C_ExecuteUbergraph_BP_AJBNetworkTestProxy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBNetworkTestProxy.BP_AJBNetworkTestProxy_C.RequestGameServerTest
// (BlueprintCallable, BlueprintEvent)

void ABP_AJBNetworkTestProxy_C::RequestGameServerTest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBNetworkTestProxy_C", "RequestGameServerTest");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBNetworkTestProxy.BP_AJBNetworkTestProxy_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_AJBNetworkTestProxy_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBNetworkTestProxy_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBNetworkTestProxy.BP_AJBNetworkTestProxy_C.OnSuccess_A97A969547DB49218203D18F22CD930E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EAJBNetAPIResult                        Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBNetworkTestProxy_C::OnSuccess_A97A969547DB49218203D18F22CD930E(EAJBNetAPIResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBNetworkTestProxy_C", "OnSuccess_A97A969547DB49218203D18F22CD930E");

	Params::BP_AJBNetworkTestProxy_C_OnSuccess_A97A969547DB49218203D18F22CD930E Parms{};

	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBNetworkTestProxy.BP_AJBNetworkTestProxy_C.OnFailed_A97A969547DB49218203D18F22CD930E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EAJBNetAPIResult                        Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBNetworkTestProxy_C::OnFailed_A97A969547DB49218203D18F22CD930E(EAJBNetAPIResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBNetworkTestProxy_C", "OnFailed_A97A969547DB49218203D18F22CD930E");

	Params::BP_AJBNetworkTestProxy_C_OnFailed_A97A969547DB49218203D18F22CD930E Parms{};

	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBNetworkTestProxy.BP_AJBNetworkTestProxy_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_AJBNetworkTestProxy_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBNetworkTestProxy_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

