#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBSpotLightComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AJBSpotLightComponent.BP_AJBSpotLightComponent_C
// 0x0010 (0x03C0 - 0x03B0)
class UBP_AJBSpotLightComponent_C final : public USpotLightComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B0(0x0008)(Transient, DuplicateTransient)
	class UBP_AJBInGameLastSurvivorSceneDirector_C* LastSurvivorSceneDirector;                       // 0x03B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_AJBSpotLightComponent(int32 EntryPoint);
	void OnEndInGameOpeningCountDown();
	void OnStartInGameOpeningCountDown();
	void OnBeginVictoryShot_Shot(const struct FGameplayTag& PrevState);
	void ReceiveBeginPlay();
	void OnEndLastSurvivorCut(uint8 CurrentCut, uint8 NextCut);
	void OnBeginLastSurvivorCut(uint8 CurrentCut, uint8 BeforeCut);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AJBSpotLightComponent_C">();
	}
	static class UBP_AJBSpotLightComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AJBSpotLightComponent_C>();
	}
};
static_assert(alignof(UBP_AJBSpotLightComponent_C) == 0x000008, "Wrong alignment on UBP_AJBSpotLightComponent_C");
static_assert(sizeof(UBP_AJBSpotLightComponent_C) == 0x0003C0, "Wrong size on UBP_AJBSpotLightComponent_C");
static_assert(offsetof(UBP_AJBSpotLightComponent_C, UberGraphFrame) == 0x0003B0, "Member 'UBP_AJBSpotLightComponent_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_AJBSpotLightComponent_C, LastSurvivorSceneDirector) == 0x0003B8, "Member 'UBP_AJBSpotLightComponent_C::LastSurvivorSceneDirector' has a wrong offset!");

}

