#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPF_AJBOutGameHUD

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPF_AJBOutGameHUD.BPF_AJBOutGameHUD_C
// 0x0000 (0x0028 - 0x0028)
class UBPF_AJBOutGameHUD_C final : public UBlueprintFunctionLibrary
{
public:
	static void GetAJBOutGameHUD_BP(int32 PlayerIndex, class UObject* __WorldContext, bool* bSuccess, class ABP_AJBOutGameHUD_C** Out_Game_HUD);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPF_AJBOutGameHUD_C">();
	}
	static class UBPF_AJBOutGameHUD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPF_AJBOutGameHUD_C>();
	}
};
static_assert(alignof(UBPF_AJBOutGameHUD_C) == 0x000008, "Wrong alignment on UBPF_AJBOutGameHUD_C");
static_assert(sizeof(UBPF_AJBOutGameHUD_C) == 0x000028, "Wrong size on UBPF_AJBOutGameHUD_C");

}

